refactor: streamline test execution and API documentation generation in pre-push hook

diff --git a/blueprint/tools/git-hooks/hooks/pre-push b/blueprint/tools/git-hooks/hooks/pre-push
--- a/blueprint/tools/git-hooks/hooks/pre-push
+++ b/blueprint/tools/git-hooks/hooks/pre-push
@@ -9,35 +9,43 @@ if [ -f "$GIT_DIR/MERGE_HEAD" ]; then
     exit 0
 fi
 
-# Check if phpunit is installed or pest and run the tests accordingly - don't exit
-if bash "$runner" composer show | grep -q "pestphp/pest"; then
-    echo "Running Pest tests..."
-    bash "$runner" composer test:coverage
-    echo "Tests passed successfully"
-fi
+function run_tests() {
+    local test_tool=$1
+    local test_command=$2
 
-if bash "$runner" composer show | grep -q "phpunit/phpunit"; then
-    echo "Running PHPUnit tests..."
-    bash "$runner" composer test:coverage
-    echo "Tests passed successfully"
-fi
+    if bash "$runner" composer show | grep -q "$test_tool"; then
+        echo "Running $test_tool tests..."
+        bash "$runner" composer "$test_command"
+        echo "Tests passed successfully"
+    fi
+}
 
-# Check if swagger-php is installed
-if ! bash "$runner" composer show | grep -q "zircote/swagger-php"; then
-    echo "swagger-php is not installed. Skipping API documentation generation..."
-    exit 0
-fi
+function generate_api_docs() {
+    # Check if swagger-php is installed
+    if ! bash "$runner" composer show | grep -q "zircote/swagger-php"; then
+        echo "swagger-php is not installed. Skipping API documentation generation..."
+        exit 0
+    fi
 
-if ! bash "$runner" composer generate-api-spec; then
-    echo "Failed to generate the API documentation"
-    exit 1
-fi
+    # Generate API documentation
+    if ! bash "$runner" composer generate-api-spec; then
+        echo "Failed to generate the API documentation"
+        exit 1
+    fi
 
-# Check if openapi.yml has been modified and exit if it's not
-git diff --name-only | grep -q openapi.yml || exit 0
+    # Check if openapi.yml has been modified and exit if it's not
+    git diff --name-only | grep -q openapi.yml || exit 0
 
-# Generate the HTML API documentation
-bash "$runner" pnpm generate:api-doc:html
+    # Generate the HTML API documentation
+    bash "$runner" pnpm generate:api-doc:html
 
-git add documentation
-git commit -m "chore: update API documentation"
+    git add documentation
+    git commit -m "chore: update API documentation"
+}
+
+# Run Pest or PHPUnit tests
+run_tests "pestphp/pest" "test:coverage"
+run_tests "phpunit/phpunit" "test:coverage"
+
+# Generate API documentation if necessary
+generate_api_docs
